name: Build

on:
  pull_request:

env:
  DOTNET_VERSION: 8.0.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Use .NET ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build & Test project
      run: dotnet test

    - name: Lint C# code
      run: dotnet format --verify-no-changes --verbosity detailed --no-restore

    - name: Lint Bicep template
      run: az bicep build -f azuredeploy.bicep
