name: Release

on:
  push:
    tags: [ v* ]

env:
  DOTNET_VERSION: 7.0.x

jobs:
  publish:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.setup_version.outputs.version }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Use .NET Core ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Setup Version
      id: setup_version
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT

    - name: Publish Functions
      run: dotnet publish ${{ github.workspace }}/Kerbee/Kerbee.csproj -c Release -o ./dist -p:Version=${{ steps.setup_version.outputs.version }}

    - name: Zip Functions
      run: |
        pushd ./dist
        zip -r kerbee.zip ./
        popd

    - name: Create ${{ github.ref }} release
      uses: softprops/action-gh-release@v1
      with:
        files: ./dist/kerbee.zip